# -*- coding: utf-8 -*-
"""Copy of learning project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrtPSnMjWNORzXa9CxAjC7PEkoWEaI9W
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(page_title="Stress Calculator", page_icon="🧮")
# 
# st.title("🧱 Stress Calculator (P/A ± M/Z)")
# st.write("Enter the values below to calculate maximum and minimum stresses:")
# 
# P = st.number_input("Axial Load P", value=0.0, step=0.1)
# A = st.number_input("Area A", value=1.0, step=0.1)
# M = st.number_input("Moment M", value=0.0, step=0.1)
# Z = st.number_input("Section Modulus Z", value=1.0, step=0.1)
# 
# if st.button("Calculate"):
#     if A == 0 or Z == 0:
#         st.error("❌ Area (A) and Section Modulus (Z) cannot be zero.")
#     else:
#         sigma_axial = P / A
#         sigma_bending = M / Z
#         sigma_max = sigma_axial + sigma_bending
#         sigma_min = sigma_axial - sigma_bending
# 
#         st.success("✅ Results Calculated")
#         st.metric("Maximum Stress σmax", f"{sigma_max:.3f}")
#         st.metric("Minimum Stress σmin", f"{sigma_min:.3f}")
# 
#         if sigma_min < 0:
#             st.warning("⚠️ Minimum stress is tensile (possible cracking zone).")
#         else:
#             st.info("🧩 All compressive stresses (safe zone).")
#

!streamlit run app.py --server.headless true --server.port 8501 &
